# Generated by Django 4.1.5 on 2023-02-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
